import { describe, expect, it } from "vitest";
import { invoiceLabels, logoFallback } from "../shared/invoiceLabels";
import { defaultCopyrightFooter } from "../shared/printLabels";

describe("invoice branding contract", () => {
  it("supports Bengali and English invoice label modes", () => {
    expect(invoiceLabels("bn").invoice).toBe("চালান");
    expect(invoiceLabels("bn").total).toContain("সর্বমোট");
    expect(invoiceLabels("en").invoice).toBe("INVOICE");
    expect(invoiceLabels("en").total).toBe("Total");
    expect(invoiceLabels("en").invoiceNo).toBe("Invoice no.");
    expect(invoiceLabels("en").date).toBe("Date");
    expect(invoiceLabels("en").item).toBe("Item");
    expect(invoiceLabels("en").qty).toBe("Qty");
    expect(invoiceLabels("en").rate).toBe("Rate");
    expect(invoiceLabels("en").amount).toBe("Amount");
    expect(invoiceLabels("en").signature).toBe("Authorized signature");
    expect(invoiceLabels("en").thanks).toBe("Thank you");
    expect(invoiceLabels("bn").invoiceNo).toBe("নং");
    expect(invoiceLabels("bn").total).toContain("সর্বমোট");
    expect(invoiceLabels("bn").signature).toContain("Authorized");
  });

  it("provides a safe logo initial and copyright fallback", () => {
    expect(logoFallback("Motive Ledger")).toBe("M");
    expect(logoFallback("  ")).toBe("M");
    expect(defaultCopyrightFooter("")).toContain("Nazmus Sakib");
    expect(invoiceLabels("en").notesBody).toContain("invoice");
    expect(invoiceLabels("bn").notesBody).toContain("পণ্য");
    expect(invoiceLabels("en").generatedBy).toBe("Generated by Car Shop Ledger");
  });
});
