export type InvoiceLanguage = "bn" | "en";

export function invoiceLabels(language: InvoiceLanguage = "bn") {
  return language === "en"
    ? { automotive: "Automotive parts & accessories", invoice: "INVOICE", invoiceNo: "Invoice no.", date: "Date", billTo: "Bill to", payment: "Payment status", paidStatus: "Paid", dueStatus: "Due", fullyPaid: "Fully paid", dueAmount: "Due amount", customerFallback: "Walk-in customer", phoneFallback: "No phone number", addressFallback: "Address not configured", mobileFallback: "Phone not configured", vat: "VAT/BIN", item: "Item", qty: "Qty", rate: "Rate", amount: "Amount", subtotal: "Subtotal", discount: "Discount", tax: "Tax", total: "Total", paid: "Paid", due: "Due", notes: "Terms & notes", notesBody: "Please verify the invoice and item quantities at the time of delivery. Thank you for your business.", thanks: "Thank you", thanksBody: "Thank you for your trust.", signature: "Authorized signature", generatedBy: "Generated by Car Shop Ledger", noLogo: "Company logo placeholder" }
    : { automotive: "Automotive parts & accessories", invoice: "চালান", invoiceNo: "নং", date: "তারিখ", billTo: "Bill to / ক্রেতা", payment: "Payment status", paidStatus: "পরিশোধিত / Paid", dueStatus: "বাকি আছে / Due", fullyPaid: "সম্পূর্ণ পরিশোধ হয়েছে", dueAmount: "বাকি", customerFallback: "সাধারণ ক্রেতা", phoneFallback: "মোবাইল নম্বর নেই", addressFallback: "ঠিকানা সংযুক্ত করা হয়নি", mobileFallback: "মোবাইল নম্বর সংযুক্ত করা হয়নি", vat: "VAT/BIN", item: "পণ্য / Item", qty: "পরিমাণ / Qty", rate: "দর / Rate", amount: "মোট / Amount", subtotal: "উপমোট / Subtotal", discount: "ছাড় / Discount", tax: "ভ্যাট/ট্যাক্স", total: "সর্বমোট / Total", paid: "পরিশোধ / Paid", due: "বাকি / Due", notes: "Terms & notes", notesBody: "পণ্য গ্রহণের সময় অনুগ্রহ করে invoice এবং item quantity যাচাই করুন। কৃতজ্ঞতার সাথে আপনার ব্যবসার পাশে আছি।", thanks: "ধন্যবাদ — Thank you", thanksBody: "আপনার আস্থার জন্য ধন্যবাদ।", signature: "Authorized signature", generatedBy: "Generated by Car Shop Ledger", noLogo: "Company logo placeholder" };
}

export function logoFallback(shopName: string) {
  return shopName.trim().charAt(0).toUpperCase() || "M";
}
