import { defaultCopyrightFooter, taxModeLabel } from "../../../shared/printLabels";
import { invoiceLabels, logoFallback, type InvoiceLanguage } from "../../../shared/invoiceLabels";
import { buildInvoicePrintContract } from "../../../shared/invoiceContract";

export type PrintShop = { shopName: string; address?: string | null; phone?: string | null; logoUrl?: string | null; vatNumber?: string | null; copyrightFooter?: string | null; invoiceLanguage?: InvoiceLanguage };
export type PrintSale = { invoiceNo: string; createdAt?: string | Date; customerName?: string | null; customerPhone?: string | null; items: { name: string; quantity: number; unitPrice: number; lineTotal: number }[]; subtotal: number; discount: number; taxRate: number; taxAmount: number; taxMode: "exclusive" | "inclusive"; total: number; paid: number };

const taka = (value: number) => `৳${value.toLocaleString("en-BD", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const footer = (shop: PrintShop) => defaultCopyrightFooter(shop.copyrightFooter);
const invoiceDate = (value: string | Date | undefined, language: InvoiceLanguage = "bn") => value ? new Date(value).toLocaleDateString(language === "en" ? "en-US" : "bn-BD", { day: "2-digit", month: "long", year: "numeric" }) : "—";

function BrandLogo({ shop, compact = false, label = "Company logo placeholder" }: { shop: PrintShop; compact?: boolean; label?: string }) {
  return shop.logoUrl ? <img src={shop.logoUrl} alt={`${shop.shopName} company logo`} onError={event => { event.currentTarget.style.display = "none"; }} className={`${compact ? "h-10 w-10" : "h-16 w-16"} rounded-2xl border border-slate-200 bg-white object-contain p-1.5`} /> : <div aria-label={label} className={`${compact ? "h-10 w-10 text-sm" : "h-16 w-16 text-2xl"} grid place-items-center rounded-2xl bg-[#ef8354] font-bold text-white shadow-sm`}>{logoFallback(shop.shopName)}</div>;
}

export function BanglaInvoicePrint({ shop, sale }: { shop: PrintShop; sale: PrintSale }) {
  const contract = buildInvoicePrintContract({ ...shop, ...sale }); const due = contract.totals.due; const language = contract.language; const labels = contract.labels;
  return <article className="invoice-print mx-auto max-w-4xl overflow-hidden bg-white text-[#10243f] shadow-[0_15px_45px_rgba(15,35,60,.08)] print:max-w-none print:shadow-none">
    <div className="h-2 bg-[#ef8354] print:h-1" />
    <div className="p-8 sm:p-10 print:p-0">
      <header className="flex items-start justify-between gap-6 border-b border-slate-200 pb-7">
        <div className="flex min-w-0 items-start gap-4"><BrandLogo shop={shop} label={labels.noLogo} /><div className="min-w-0"><p className="text-[10px] font-bold uppercase tracking-[0.24em] text-[#ef8354]">{labels.automotive}</p><h1 className="mt-2 truncate text-2xl font-bold tracking-[-0.04em] sm:text-3xl">{shop.shopName}</h1><div className="mt-3 space-y-1 text-xs leading-5 text-slate-500"><p>{shop.address || labels.addressFallback}</p><p>{shop.phone || labels.mobileFallback}</p>{shop.vatNumber && <p className="font-medium text-slate-600">{labels.vat}: {shop.vatNumber}</p>}</div></div></div>
        <div className="shrink-0 text-right"><p className="text-[10px] font-bold uppercase tracking-[0.22em] text-[#ef8354]">{labels.invoice}</p><h2 className="mt-2 text-2xl font-bold tracking-[-0.04em]">{labels.invoice}</h2><div className="mt-4 space-y-1 text-xs text-slate-500"><p><span className="text-slate-400">{labels.invoiceNo}</span> <strong className="text-[#10243f]">{sale.invoiceNo}</strong></p><p><span className="text-slate-400">{labels.date}</span> <strong className="text-[#10243f]">{invoiceDate(sale.createdAt, language)}</strong></p></div></div>
      </header>
      <section className="mt-7 grid gap-4 sm:grid-cols-2"><div className="rounded-2xl border border-slate-200 bg-slate-50/70 p-5"><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-slate-400">{labels.billTo}</p><p className="mt-3 text-base font-bold">{sale.customerName || labels.customerFallback}</p><p className="mt-1 text-xs text-slate-500">{sale.customerPhone || labels.phoneFallback}</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-slate-400">{labels.payment}</p><p className={`mt-3 text-base font-bold ${due > 0 ? "text-rose-500" : "text-emerald-600"}`}>{due > 0 ? labels.dueStatus : labels.paidStatus}</p><p className="mt-1 text-xs text-slate-500">{due > 0 ? `${labels.dueAmount} ${taka(due)}` : labels.fullyPaid}</p></div></section>
      <table className="invoice-items mt-8 w-full border-collapse text-sm"><thead><tr className="border-y-2 border-[#10243f] text-left text-[10px] font-bold uppercase tracking-[0.12em] text-slate-500"><th className="py-3 pr-3">{labels.item}</th><th className="w-20 py-3 text-right">{labels.qty}</th><th className="w-32 py-3 text-right">{labels.rate}</th><th className="w-36 py-3 text-right">{labels.amount}</th></tr></thead><tbody>{sale.items.map((item, index) => <tr key={`${item.name}-${index}`} className="border-b border-slate-100"><td className="py-4 pr-3 font-semibold">{item.name}</td><td className="py-4 text-right text-slate-600">{item.quantity}</td><td className="py-4 text-right text-slate-600">{taka(item.unitPrice)}</td><td className="py-4 text-right font-bold">{taka(item.lineTotal)}</td></tr>)}</tbody></table>
      <section className="mt-8 flex flex-col justify-between gap-8 sm:flex-row"><div className="max-w-sm text-xs leading-5 text-slate-500"><p className="font-bold text-[#10243f]">{labels.notes}</p><p className="mt-2">{labels.notesBody}</p></div><div className="w-full max-w-sm space-y-2 text-sm"><div className="flex justify-between"><span className="text-slate-500">{labels.subtotal}</span><b>{taka(sale.subtotal)}</b></div><div className="flex justify-between"><span className="text-slate-500">{labels.discount}</span><b>-{taka(sale.discount)}</b></div><div className="flex justify-between"><span className="text-slate-500">{labels.tax} ({sale.taxRate}% · {taxModeLabel(sale.taxMode, true)})</span><b>{taka(sale.taxAmount)}</b></div><div className="flex justify-between border-t-2 border-[#10243f] pt-4 text-lg"><span className="font-bold">{labels.total}</span><b>{taka(sale.total)}</b></div><div className="flex justify-between text-emerald-600"><span>{labels.paid}</span><b>{taka(sale.paid)}</b></div><div className="flex justify-between rounded-xl bg-rose-50 px-3 py-2 font-bold text-rose-600"><span>{labels.due}</span><span>{taka(due)}</span></div></div></section>
      <footer className="mt-14 flex flex-col justify-between gap-8 border-t border-slate-200 pt-6 text-xs text-slate-500 sm:flex-row"><div><p className="font-semibold text-[#10243f]">{labels.thanks}</p><p className="mt-2">{labels.thanksBody}</p></div><div className="w-44 border-t border-slate-300 pt-2 text-center"><p>{labels.signature}</p></div><div className="text-left sm:text-right"><p>{footer(shop)}</p><p className="mt-2 text-[10px] text-slate-400">{labels.generatedBy}</p></div></footer>
    </div>
  </article>;
}

export function ThermalReceipt({ shop, sale, width = "80mm" }: { shop: PrintShop; sale: PrintSale; width?: "58mm" | "80mm" }) {
  return <article className={`thermal-receipt thermal-${width === "58mm" ? "58" : "80"} mx-auto bg-white p-3 text-black`}><header className="text-center"><BrandLogo shop={shop} compact /><p className="mt-2 text-base font-bold">{shop.shopName}</p><p className="text-[10px]">{shop.phone || ""}</p><p className="mt-2 text-xs font-bold">{sale.invoiceNo}</p></header><div className="my-2 border-t border-dashed border-black" />{sale.items.map((item, index) => <div key={`${item.name}-${index}`} className="flex justify-between gap-2 text-[10px]"><span className="truncate">{item.name} × {item.quantity}</span><span>{taka(item.lineTotal)}</span></div>)}<div className="my-2 border-t border-dashed border-black" /><div className="space-y-1 text-[10px]"><div className="flex justify-between"><span>Subtotal</span><b>{taka(sale.subtotal)}</b></div><div className="flex justify-between"><span>Tax ({taxModeLabel(sale.taxMode)})</span><b>{taka(sale.taxAmount)}</b></div><div className="flex justify-between text-xs"><span>Total</span><b>{taka(sale.total)}</b></div><div className="flex justify-between"><span>Paid</span><b>{taka(sale.paid)}</b></div><div className="flex justify-between"><span>Due</span><b>{taka(Math.max(0, sale.total - sale.paid))}</b></div></div><div className="my-2 border-t border-dashed border-black" /><p className="text-center text-[9px]">{footer(shop)}</p></article>;
}
